version: '3.9'

services:
  springboot-api:
    container_name: springboot-api
    image: devops-springboot-api:1.0.0
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/devops
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=devops
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: